"""Reports, prescriptions, appointments API routes."""

import os
import io
from datetime import datetime
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from backend import database as db

router = APIRouter(prefix="/api/patient", tags=["Patient Reports"])

# Ensure upload directories exist
BASE_UPLOAD = os.path.join(os.path.dirname(os.path.dirname(__file__)), "..", "backend", "uploads")
for subdir in ("reports", "prescriptions", "scans"):
    os.makedirs(os.path.join(BASE_UPLOAD, subdir), exist_ok=True)


def _generate_pdf(report: dict) -> bytes:
    """Generate a real PDF report on-the-fly using reportlab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib.colors import HexColor
    from reportlab.pdfgen import canvas

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4

    # Header bar
    c.setFillColor(HexColor("#0a0e1a"))
    c.rect(0, h - 80, w, 80, fill=1, stroke=0)
    c.setFillColor(HexColor("#06b6d4"))
    c.setFont("Helvetica-Bold", 22)
    c.drawString(30, h - 45, "HealthAI")
    c.setFillColor(HexColor("#94a3b8"))
    c.setFont("Helvetica", 10)
    c.drawString(30, h - 65, "AI Healthcare Imaging Data Regulator")

    # Report title
    c.setFillColor(HexColor("#1e293b"))
    c.setFont("Helvetica-Bold", 18)
    c.drawString(30, h - 120, report.get("reportName", "Medical Report"))

    y = h - 155
    c.setFont("Helvetica", 11)
    c.setFillColor(HexColor("#475569"))

    # Metadata
    patient = next((p for p in db.patients if p["id"] == report.get("patient_id")), {})
    fields = [
        ("Patient", patient.get("name", "N/A")),
        ("Patient ID", report.get("patient_id", "N/A")),
        ("Age / Gender", f"{patient.get('age', 'N/A')} / {patient.get('gender', 'N/A')}"),
        ("Doctor", report.get("doctor", "N/A")),
        ("Report Date", report.get("uploadDate", "N/A")[:10]),
        ("Report Type", report.get("reportType", "N/A").upper()),
    ]
    for label, value in fields:
        c.setFont("Helvetica-Bold", 10)
        c.setFillColor(HexColor("#64748b"))
        c.drawString(30, y, f"{label}:")
        c.setFont("Helvetica", 10)
        c.setFillColor(HexColor("#1e293b"))
        c.drawString(140, y, str(value))
        y -= 20

    # Divider
    y -= 10
    c.setStrokeColor(HexColor("#e2e8f0"))
    c.line(30, y, w - 30, y)
    y -= 25

    # Summary
    c.setFont("Helvetica-Bold", 13)
    c.setFillColor(HexColor("#0f172a"))
    c.drawString(30, y, "Clinical Summary")
    y -= 20

    c.setFont("Helvetica", 10)
    c.setFillColor(HexColor("#334155"))
    summary = report.get("summary", "No summary available.")
    # Word-wrap
    words = summary.split()
    line = ""
    for word in words:
        test = f"{line} {word}".strip()
        if c.stringWidth(test, "Helvetica", 10) > w - 80:
            c.drawString(30, y, line)
            y -= 16
            line = word
        else:
            line = test
    if line:
        c.drawString(30, y, line)
        y -= 16

    # Imaging link
    if report.get("imaging_id"):
        y -= 15
        c.setFont("Helvetica-Bold", 13)
        c.setFillColor(HexColor("#0f172a"))
        c.drawString(30, y, "Associated Imaging Study")
        y -= 20
        c.setFont("Helvetica", 10)
        c.setFillColor(HexColor("#334155"))
        img = next((i for i in db.imaging_records if i["id"] == report["imaging_id"]), None)
        if img:
            c.drawString(30, y, f"Study: {img['type']} ({img['id']})")
            y -= 16
            c.drawString(30, y, f"Status: {img['status'].upper()}")
            y -= 16

    # Footer
    c.setFont("Helvetica", 8)
    c.setFillColor(HexColor("#94a3b8"))
    c.drawString(30, 30, f"Generated by HealthAI System — {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC")
    c.drawRightString(w - 30, 30, "CONFIDENTIAL — For authorized use only")

    c.save()
    buf.seek(0)
    return buf.read()


# ── Report endpoints ─────────────────────────────────────────

@router.get("/reports/{patient_id}")
def list_reports(patient_id: str):
    rpts = [r for r in db.reports if r["patient_id"] == patient_id]
    return {"reports": rpts}


@router.get("/reports/{report_id}/download")
def download_report(report_id: str):
    report = next((r for r in db.reports if r["id"] == report_id), None)
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    pdf_bytes = _generate_pdf(report)
    filename = f"{report['reportName'].replace(' ', '_')}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/report-detail/{report_id}")
def get_report_detail(report_id: str):
    report = next((r for r in db.reports if r["id"] == report_id), None)
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    patient = next((p for p in db.patients if p["id"] == report["patient_id"]), {})
    imaging = None
    if report.get("imaging_id"):
        imaging = next((i for i in db.imaging_records if i["id"] == report["imaging_id"]), None)
    return {"report": report, "patient": patient, "imaging": imaging}


# ── Prescriptions ────────────────────────────────────────────

@router.get("/prescriptions/{patient_id}")
def list_prescriptions(patient_id: str):
    prescs = [p for p in db.prescriptions if p["patient_id"] == patient_id]
    return {"prescriptions": prescs}


# ── Appointments ─────────────────────────────────────────────

@router.get("/appointments/{patient_id}")
def list_appointments(patient_id: str):
    apts = [a for a in db.appointments if a["patient_id"] == patient_id]
    return {"appointments": apts}
